name: pullrequest
on:
	pull_request:
		branches:
			- master

jobs:
	installDependances:
		runs-on: ubuntu-latest

		steps:
			- uses: actions/checkout@v4
			- name: installNodeJs
				uses: actions/setup-node@v3
			- run: npm ci 
			- run: npm run test